// TypesFromSerializers CacheKey 2e5ba5dae8cba142e874cd2a4aa6f560
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: number
      email: string
      name: string
    }
  }
}
